package org.lrima.laop.simulation.data;

import org.lrima.laop.utils.CSVUtils;

import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.function.Consumer;
import java.util.stream.Collectors;

/**
 * Class to manage data generated by the algorithms during or at the end of a simulation
 * @author Clement Bisaillon
 */
public class AlgorithmData extends ArrayList<ArrayList<Double>> {
    private Date start = new Date();
    private HashMap<String, ArrayList<Double>> values = new HashMap<>();
    private Consumer<String> valueAdded;

    /**
     * Export the data to a csv file for better inspection
     *
     * @param prefix the prefix that the csv file is going to have
     */
    public void toCsv(String prefix) {
        //Create a directory with the time of the simulation start in /data
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/d/HH-mm-ss");
        for(String scope : values.keySet()) {
            String directory = "data/" + dateFormat.format(this.start);
            File file = new File(directory, prefix + "-" + scope + ".csv");
            boolean created = file.getParentFile().mkdirs();

            ArrayList<String> values = this.values.get(scope).stream()
                    .map(d -> d + "")
                    .collect(Collectors.toCollection(ArrayList::new));

            CSVUtils.createCSVFile(file, (writer) ->{
                try {
                    CSVUtils.writeLine(writer, values);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            });
        }
    }

    /**
     * Add data to the algorithmData
     *
     * @param scope the scope to add it to
     * @param data the data
     */
    public void put(String scope, Double data){
        values.computeIfAbsent(scope, k -> new ArrayList<>());
        this.values.get(scope).add(data);
        if(valueAdded != null)
            valueAdded.accept(scope);
    }

    /**
     * Gets all the collected data
     *
     * @return the data
     */
    public HashMap<String, ArrayList<Double>> getData(){
        return values;
    }

    /**
     * Adds a listener that is called each time a data is added
     *
     * @param stringConsumer the consumer to call. The string value in the consumer is the key
     */
    public void setOnAddValue(Consumer<String> stringConsumer){
        this.valueAdded = stringConsumer;
    }
}
